In [1]:
from scripts.applications.prediction_models.models.syntax_infused_model import *
from scripts.applications.prediction_models.models.sequential_model import *

In [2]:
import numpy as np
import random

In [3]:
cnt_channels = 19

In [4]:
combine_model = SimpleConcatCombing()

In [5]:
combine_model.forward(torch.FloatTensor([1,2,3]).reshape((1, 3)), torch.FloatTensor([4,5,6]).reshape((1, 3)))

tensor([[1., 2., 3., 4., 5., 6.]])

In [6]:
def generate_random_eeg_data(cnt_channels = 19, cnt_time_samples = 1000): # unit: mV
    return 0.1 * np.random.random_sample((cnt_channels, cnt_time_samples)) * 90

def generate_random_segmented_eeg_data(cnt_channels = 19, cnt_time_samples = 1000): # unit: mV
    dummy_eeg_data = generate_dummy_eeg_data(cnt_channels, cnt_time_samples)
    split_points = [0]
    p = np.random()
    for i in range(1, cnt_time_samples):
        if np.random() < p:
            split_points.append(i)
    split_points.append(cnt_time_samples)
    return [dummy_eeg_data[split_points[i - 1], split_points[i]] for i in range(1, len(split_points))]

def generate_random_corpus(word_count, cnt_article, article_max_length):
    return [np.random.randint(0, word_count, size = (np.random.randint(0, article_max_length))) for _ in range(cnt_article)]
    
    
dummy_eeg_data = generate_random_eeg_data(cnt_channels = cnt_channels)
dummy_eeg_data

array([[6.61093167, 8.93916759, 3.32544012, ..., 2.40559571, 6.42024419,
        4.58814777],
       [8.47971132, 1.28336328, 5.26855733, ..., 4.12245052, 0.69559637,
        4.35878282],
       [2.79336951, 2.67877383, 1.86943541, ..., 8.92799928, 6.70696551,
        7.29514037],
       ...,
       [8.36377464, 7.4707776 , 1.63352423, ..., 4.02458066, 0.10104893,
        5.66730342],
       [8.73089803, 7.15550573, 6.24167123, ..., 2.53117518, 6.00697847,
        5.8810845 ],
       [2.89067465, 2.25746409, 5.0403024 , ..., 5.27413092, 0.44462482,
        4.53336194]])

In [7]:
LNN_electrode_value_based_prediction_model = LNNElectrodeValueBasedPredictionModel(ncp_input_size = cnt_channels, hidden_size=100, output_size=1, sequence_length=1)

In [8]:
h = LNN_electrode_value_based_prediction_model.h
for t in range(dummy_eeg_data.shape[1]):
    input_t = torch.Tensor(dummy_eeg_data[:, t])
    out, h = LNN_electrode_value_based_prediction_model.forward(input_t)
h

tensor([[ 0.8468, -0.4345, -0.1769,  0.8571,  0.9551,  0.2765, -0.4420, -0.8114,
          0.0125,  0.2116, -0.6061,  0.9293,  0.5590, -0.5634,  0.5849,  0.5097,
         -0.3498,  0.3913, -0.3887, -0.0407,  0.8222, -0.7162,  0.6127,  0.9055,
         -0.9843, -0.5363, -0.5307, -0.0566, -0.1090,  0.7507,  0.6353,  0.9156,
          0.9794, -0.5122, -0.9736,  0.2356, -0.5210, -0.9712,  0.3747,  0.9701,
         -0.9725,  0.9833,  0.9764, -0.9958,  0.3756,  0.9901, -0.8557,  0.9963,
         -0.8825, -0.9987, -0.9274, -0.9365,  0.9951,  0.4454,  0.5206,  0.4205,
          0.6519,  0.9413,  0.3069, -0.8439, -0.4049, -0.2272,  0.0011, -0.4366,
         -0.2144,  0.1758, -0.6006,  0.3736,  0.4142,  0.4450, -0.4707,  0.1703,
          0.1888, -0.1997, -0.4669, -0.0093,  0.4519, -0.1484, -0.0800, -0.3569,
         -0.3658, -0.3318,  0.2351,  0.1130, -0.3999, -0.1000, -0.2881, -0.5257,
         -0.1844, -0.3167, -0.1798, -0.3345,  0.1102, -0.2472, -0.2113, -0.1933,
          0.3787,  0.3399,  

In [9]:
from scripts.applications.prediction_models.models.neural_cky import *

In [10]:
from scripts.language_processing.language_builder.neural_builder.models.tn_pcfg import TNPCFG

In [11]:
word_count = 10
args = {'NT': 20,
              'T': 10,
              'V': 25,
              's_dim': 50,
              'r_dim': 75,
              'word_emb_size': 200,
            'cnt_words': word_count,
            'summary_parameters': True,
        }

In [12]:
tn_pcfg = TNPCFG(args=args)
print(f"{tn_pcfg}")

build td pcfg
device = cpu, NT = 20, T = 10, V = 10, s_dim = 50, r = 75, word_emb_size = 200
TNPCFG(
  (root_mlp): Sequential(
    (0): Linear(in_features=50, out_features=50, bias=True)
    (1): ResLayer(
      (linear): Sequential(
        (0): Linear(in_features=50, out_features=50, bias=True)
        (1): ReLU()
        (2): Linear(in_features=50, out_features=50, bias=True)
        (3): ReLU()
      )
    )
    (2): ResLayer(
      (linear): Sequential(
        (0): Linear(in_features=50, out_features=50, bias=True)
        (1): ReLU()
        (2): Linear(in_features=50, out_features=50, bias=True)
        (3): ReLU()
      )
    )
    (3): Linear(in_features=50, out_features=20, bias=True)
  )
  (term_mlp): Sequential(
    (0): Linear(in_features=50, out_features=50, bias=True)
    (1): ResLayer(
      (linear): Sequential(
        (0): Linear(in_features=50, out_features=50, bias=True)
        (1): ReLU()
        (2): Linear(in_features=50, out_features=50, bias=True)
        (3

In [13]:
# generate grammars
corpus = generate_random_corpus(word_count, 1000, 2000)

In [14]:
inference = tn_pcfg.forward(input={'word':(np.array(corpus[0])).reshape((1, len(corpus[0])))})

begin forward>>>>>>>>>>>>>
x = [[4 7 3 ... 8 0 3]]
b, n = 1, 1918
torch.Size([1, 1918, 10]) torch.Size([1, 20]) torch.Size([1, 20, 75]) torch.Size([1, 30, 75]) torch.Size([1, 30, 75])


In [15]:
print(inference.keys())

dict_keys(['unary', 'root', 'head', 'left', 'right', 'kl'])


In [16]:
word_embeddings = np.random.random((args['cnt_words'], args['word_emb_size']))
word_embeddings.shape

(10, 200)

In [17]:
args['word_embeddings'] = word_embeddings
args['grammar_starts'] = np.random.random((args['NT'])) # |NT|
args['grammar_preterminates'] = np.random.random((args['T'], args['cnt_words']))
args['grammar_double_nonterminates'] = np.random.random((args['NT'], args['NT'] + args['T'], args['NT'] + args['T']))
# {
#     'head': np.random.random((args['NT'])),
#     'left': np.random.random((args['NT'] + args['T'], args['r_dim'])),
#     'right': np.random.random((args['NT'] + args['T'], args['r_dim']))
# }
args['beam_search_strategy'] = select_tops
args['preterminate_feature_generation_model'] = NN_CYK_FeatureCombingModel_Preterminate()
args['merge_model'] = NN_CYK_FeatureCombingModel_NonPreterminate()

In [18]:
nn_cyk_model = NN_CYK_Model(args)

In [19]:
nn_cyk_model.forward(5)

append record.


tensor([ 0.4668, -0.0914, -0.0597,  0.0257,  0.5473,  0.5327, -0.6843,  0.1332,
         0.0215, -0.1416, -0.2990, -0.3282, -0.4808,  0.2777, -0.0633, -0.3475,
         0.4123, -0.2773, -0.4382,  0.2646, -0.3550, -0.2539,  0.1951, -0.0372,
        -0.5159, -0.2372,  0.0810, -0.6204,  0.1208, -0.0879,  0.2783, -0.5161,
         0.1207,  0.2633, -0.1748,  0.4342,  0.3512,  0.4601, -0.2779, -0.1357,
        -0.1476,  0.4483, -0.2155,  0.6270, -0.3612,  0.1184, -0.6946, -0.0033,
        -0.3901, -0.3170, -0.4788,  0.1412, -0.0192, -0.0862,  0.5549, -0.6582,
        -0.0638, -0.1696, -0.3395, -0.6679,  0.6219,  0.0435,  0.7426,  0.1507,
        -0.1523,  0.1902, -0.3370,  0.2564,  0.3449,  0.1156,  0.2003,  0.6187,
        -0.1435,  0.2647, -0.5578, -0.3411, -0.1478, -0.1080,  0.3060, -0.0727,
        -0.1655,  0.0147,  0.6436, -0.3953,  0.0308, -0.2577, -0.0719, -0.1505,
         0.0882,  0.3293, -0.7711,  0.4500,  0.3981,  0.4047,  0.0097,  1.0541,
        -0.4591,  0.2143, -0.4267, -0.36

In [21]:
nn_cyk_model.forward(5)

append record.
fill record in t=2
fill record in t=2


tensor([ 0.1327, -0.0408,  0.1660, -0.0067, -0.0050, -0.0329, -0.2295,  0.0110,
        -0.2688, -0.0360,  0.0494, -0.0606, -0.0142, -0.1367, -0.1064,  0.0758,
        -0.0833,  0.0016, -0.0714, -0.0790, -0.0156,  0.2178,  0.0140,  0.0349,
        -0.1937, -0.1742,  0.0794, -0.0082, -0.0268,  0.0720, -0.0089, -0.0523,
        -0.0655,  0.0516, -0.0920,  0.1046,  0.1067, -0.0834, -0.1225,  0.0638,
         0.0485, -0.0227,  0.0475,  0.0968, -0.0388, -0.0287,  0.0400,  0.0413,
         0.0077,  0.0189,  0.0807,  0.0178,  0.0992, -0.1170, -0.0810,  0.0662,
        -0.1093,  0.0267, -0.1925, -0.0331,  0.0899,  0.1006, -0.0826, -0.1027,
         0.0941,  0.0573,  0.0883, -0.1002, -0.1942, -0.0208,  0.0398,  0.0158,
         0.0838,  0.2320,  0.1234,  0.1301, -0.1315,  0.1585,  0.1541, -0.0392,
         0.0300,  0.1898,  0.0880,  0.1720,  0.1906,  0.0647,  0.0554,  0.0655,
        -0.2133, -0.1142, -0.0714,  0.1715, -0.1527, -0.0575,  0.0538, -0.1610,
         0.1214,  0.1841, -0.2147, -0.02