In [9]:
from scripts.applications.prediction_models.models.syntax_infused_model import *
from scripts.applications.prediction_models.models.sequential_model import *

In [10]:
import numpy as np
import random

In [11]:
cnt_channels = 19

In [12]:
combine_model = SimpleConcatCombing()

In [13]:
combine_model.forward(torch.FloatTensor([1,2,3]).reshape((1, 3)), torch.FloatTensor([4,5,6]).reshape((1, 3)))

tensor([[1., 2., 3., 4., 5., 6.]])

In [14]:
def generate_dummy_eeg_data(cnt_channels = 19, cnt_time_samples = 1000): # unit: mV
    return 0.1 * np.random.random_sample((cnt_channels, cnt_time_samples)) * 90

def generate_dummy_segmented_eeg_data(cnt_channels = 19, cnt_time_samples = 1000): # unit: mV
    dummy_eeg_data = generate_dummy_eeg_data(cnt_channels, cnt_time_samples)
    split_points = [0]
    p = np.random()
    for i in range(1, cnt_time_samples):
        if np.random() < p:
            split_points.append(i)
    split_points.append(cnt_time_samples)
    return [dummy_eeg_data[split_points[i - 1], split_points[i]] for i in range(1, len(split_points))]
    
dummy_eeg_data = generate_dummy_eeg_data(cnt_channels = cnt_channels)
dummy_eeg_data

array([[6.40725893, 2.33350796, 7.16178078, ..., 5.07286925, 1.12143862,
        3.96634531],
       [5.91140066, 2.27443196, 8.13963478, ..., 7.50539359, 7.22955575,
        3.69727003],
       [7.75816203, 4.15557106, 0.46508821, ..., 2.0678911 , 8.33609754,
        2.75881871],
       ...,
       [3.41179886, 3.72035128, 4.57311695, ..., 8.10174545, 6.2088889 ,
        8.29060135],
       [8.74951545, 2.90432783, 6.97068217, ..., 1.79318705, 6.08605648,
        6.67671671],
       [1.0442217 , 7.53282732, 0.33937519, ..., 8.31481991, 1.74818768,
        6.95800505]])

In [15]:
LNN_electrode_value_based_prediction_model = LNNElectrodeValueBasedPredictionModel(ncp_input_size = cnt_channels, hidden_size=100, output_size=1, sequence_length=1)

In [19]:
h = LNN_electrode_value_based_prediction_model.h
for t in range(dummy_eeg_data.shape[1]):
    input_t = torch.Tensor(dummy_eeg_data[:, t])
    out, h = LNN_electrode_value_based_prediction_model.forward(input_t)
h

 - out = -0.371234
 - out = 0.157843
 - out = 0.272720
 - out = 0.123470
 - out = -0.206397
 - out = -0.444598
 - out = -0.306003
 - out = -0.257932
 - out = -0.178447
 - out = 0.226151
 - out = 0.334296
 - out = -0.118381
 - out = -0.208035
 - out = -0.643495
 - out = -0.525917
 - out = -0.126895
 - out = -0.289026
 - out = -0.382063
 - out = -0.567804
 - out = -0.329598
 - out = -0.180816
 - out = -0.049934
 - out = -0.212397
 - out = -0.231208
 - out = -0.301584
 - out = -0.558356
 - out = -0.507706
 - out = -0.192014
 - out = 0.069322
 - out = 0.196390
 - out = 0.542838
 - out = 0.339289
 - out = 0.595135
 - out = 0.183199
 - out = 0.161149
 - out = -0.066241
 - out = 0.323455
 - out = 0.407111
 - out = -0.039578
 - out = 0.476311
 - out = 0.177692
 - out = -0.199025
 - out = 0.118691
 - out = 0.577686
 - out = -0.360047
 - out = -0.401775
 - out = -0.270079
 - out = 0.013904
 - out = 0.100571
 - out = 0.000439
 - out = -0.014641
 - out = 0.177945
 - out = -0.132172
 - out = -0.282

tensor([[ 0.2124, -0.9995, -0.3727,  0.8128,  0.7679, -0.5638,  0.5222,  0.5254,
         -0.1873,  0.9465, -0.9457,  0.7928, -0.9168, -0.7736, -0.6341, -0.2242,
          0.5651, -0.9294,  0.6026,  0.0245, -0.4513,  0.2714, -0.0217,  0.2059,
          0.3238, -0.5216,  0.6084, -0.5779, -0.1553,  0.7787, -0.9775,  0.9985,
         -0.9437, -0.6963, -0.8348,  0.1781,  0.0271, -0.5651,  0.6549,  0.8689,
          0.5823,  0.1554, -0.1681,  0.5584, -0.2907,  0.6267,  0.9886,  0.3706,
          0.6688,  0.8732,  0.8074, -0.8420,  0.0342, -0.8489, -0.9813,  0.9486,
          0.1686, -0.9059,  0.4179,  0.0842, -0.0310,  0.2649, -0.3398, -0.4574,
         -0.1749,  0.0486,  0.4157, -0.0435, -0.4215, -0.4559, -0.0556,  0.5330,
         -0.5046, -0.4836, -0.6954,  0.2190,  0.1477,  0.0686,  0.3957,  0.0102,
          0.2357, -0.3642, -0.6750, -0.0131,  0.3231, -0.0929,  0.1154,  0.3484,
          0.1731,  0.1089, -0.2201,  0.5272,  0.1219,  0.1076,  0.4333,  0.2671,
         -0.0757, -0.2933, -